[package]
name = "gitgraph-analyze"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
gitgraph-core = { path = "../gitgraph-core" }
leiden-rs = { version = "0.8", optional = true }
petgraph.workspace = true
serde.workspace = true

[features]
default = []
leiden = ["dep:leiden-rs"]
