[package]
name = "gitgraph-parse"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
gitgraph-core = { path = "../gitgraph-core" }
ignore.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true

